---
- hosts: all
  become: yes


  tasks:
    - name: Add or modify hard nofile limits for wildcard domain
      pam_limits:
        domain: '*'
        limit_type: '-'
        limit_item: nofile
        value: 39693561